# Generated by Django 2.0.1 on 2018-07-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='like_num',
            new_name='liked_num',
        ),
        migrations.RenameField(
            model_name='likerecord',
            old_name='like_time',
            new_name='liked_time',
        ),
    ]
