# Generated by Django 2.0.1 on 2018-01-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
